Revert "Convert spirv-llvm to Android.bp"
This reverts commit 55583ec8430c9ac403ddce6591bc23ba42568ad5.

Broke a build:
out/host/linux-x86/obj/lib/libSPIRV.so: error: undefined reference to 'typeinfo for llvm::ModulePass'
out/host/linux-x86/obj/lib/libSPIRV.so: error: undefined reference to 'typeinfo for llvm::Instruction'
out/host/linux-x86/obj/lib/libSPIRV.so: error: undefined reference to 'typeinfo for llvm::cl::GenericOptionValue'
out/host/linux-x86/obj/lib/libSPIRV.so: error: undefined reference to 'typeinfo for llvm::UnaryInstruction'
out/host/linux-x86/obj/lib/libSPIRV.so: error: undefined reference to 'typeinfo for llvm::CmpInst'
out/host/linux-x86/obj/lib/libSPIRV.so: error: undefined reference to 'typeinfo for llvm::cl::Option'

Change-Id: I01a106fddaab6035dd493ac7f7ca5c3b013cd102